### PR TITLE
Update catalog git ref to v15

### LINKED ISSUE #441: Lower the memory limits for the workshop quickstarts
Lower the memory limit of Vert.x Basic and Healthcheck projects from 512MB to under 300MB. Lower the memory limit of Spring Boot Basic and Healthcheck projects from 512MB to under 300MB.   The goal is to allow end-users to run up to 3 pods (3 applications/3 codebases) in -stage and/or -run and still allow for rolling updates against any one of those 3 pods.

related to #442

### PR DESCRIPTION
**Pull request by gastaldi**
As an attempt to fix https://github.com/openshiftio/openshift.io/issues/441

### CODE REVIEW

**Comment by maxandersen** [comment]
we don't have the testing the quickstarts on osio running yet, do we ? 

then please be ready to test all the quickstarts as in the past updates to the catalog resulted in some kinda of havoc.

**Comment by gastaldi** [comment]
@ldimaggi should be able to answer that afaik

**Comment by maxandersen** [comment]
@gastaldi i'm referring to the tests we talked back in ireland on getting setup on launch side against osio.

**Comment by corinnekrych** [comment]
@gastaldi @maxandersen trying to upgrade to `v15` locally, I run into:
```
2017-12-08 14:11:37,772 SEVERE [io.openshift.booster.catalog.BoosterCatalogService] (ForkJoinPool.commonPool-worker-1) Error while indexing: Cannot create property=supportedDeploymentTypes for JavaBean=Booster [id=null, githubRepo=bucharest-gold/nodejs-rest-http-secured, gitRef=v1.0.0, buildProfile=null, description=No description available, boosterDescriptorPath=.openshiftio/booster.yaml, mission=null, runtime=null, version=null, contentPath=null, metadata={}, labels=[]]
 in 'reader', line 1, column 1:
    githubRepo: bucharest-gold/nodej ... 
    ^
Unable to find property 'supportedDeploymentTypes' on class: io.openshift.booster.catalog.Booster
 in 'reader', line 3, column 27:
    supportedDeploymentTypes: zip
                              ^

	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:313)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:190)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:346)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:184)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:143)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:129)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:505)
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:465)
	at io.openshift.booster.catalog.BoosterCatalogService.indexBooster(BoosterCatalogService.java:223)
	at io.openshift.booster.catalog.BoosterCatalogService.access$000(BoosterCatalogService.java:59)
	at io.openshift.booster.catalog.BoosterCatalogService$1.visitFile(BoosterCatalogService.java:154)
	at io.openshift.booster.catalog.BoosterCatalogService$1.visitFile(BoosterCatalogService.java:139)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at io.openshift.booster.catalog.BoosterCatalogService.indexBoosters(BoosterCatalogService.java:138)
	at io.openshift.booster.catalog.BoosterCatalogService.doIndex(BoosterCatalogService.java:117)
	at io.openshift.booster.catalog.BoosterCatalogService.lambda$index$0(BoosterCatalogService.java:100)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: org.yaml.snakeyaml.error.YAMLException: Unable to find property 'supportedDeploymentTypes' on class: io.openshift.booster.catalog.Booster
	at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:132)
	at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:121)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.getProperty(Constructor.java:323)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:241)
	... 22 more
```

**Comment by gastaldi** [comment]
Thanks @corinnekrych, this is one of the reasons why forking code is bad :)

I'll provide a PR to the addon to match the dependency version we use in launcher.  Can you test with that too?

**Comment by gastaldi** [comment]
https://github.com/fabric8io/fabric8-generator/pull/82 should be merged before this PR

**Comment by gastaldi** [comment]
Closing this, as work is only done in https://github.com/fabric8-launcher/launcher-backend now

**Pull request closed without merging**
